services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/database
      - JWT_SECRET=value_cang
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://localhost:3000
      # Nếu frontend và backend đều trong Docker và muốn gọi nội bộ thì dùng:
      # - VITE_API=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
